// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkV42CXZRgmppMSG_yUek-SwCJ3n12fk4',
    appId: '1:952602738159:web:fb3a732b211fbeb638ca1a',
    messagingSenderId: '952602738159',
    projectId: 'donime-e1b0b',
    authDomain: 'donime-e1b0b.firebaseapp.com',
    storageBucket: 'donime-e1b0b.appspot.com',
    measurementId: 'G-TPMBGYEZK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzv7SaCXOLjjcldbt_bW6JoVdJ8K25WU',
    appId: '1:952602738159:android:e90c4e72466dcba238ca1a',
    messagingSenderId: '952602738159',
    projectId: 'donime-e1b0b',
    storageBucket: 'donime-e1b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgBGfidlJkPyve0po_VLW2EpQTYEOkXr8',
    appId: '1:952602738159:ios:92bb7f035ec05c1538ca1a',
    messagingSenderId: '952602738159',
    projectId: 'donime-e1b0b',
    storageBucket: 'donime-e1b0b.appspot.com',
    iosBundleId: 'com.example.doniMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgBGfidlJkPyve0po_VLW2EpQTYEOkXr8',
    appId: '1:952602738159:ios:92bb7f035ec05c1538ca1a',
    messagingSenderId: '952602738159',
    projectId: 'donime-e1b0b',
    storageBucket: 'donime-e1b0b.appspot.com',
    iosBundleId: 'com.example.doniMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkV42CXZRgmppMSG_yUek-SwCJ3n12fk4',
    appId: '1:952602738159:web:8f997b6c9e45cdd938ca1a',
    messagingSenderId: '952602738159',
    projectId: 'donime-e1b0b',
    authDomain: 'donime-e1b0b.firebaseapp.com',
    storageBucket: 'donime-e1b0b.appspot.com',
    measurementId: 'G-KGSNF01VLZ',
  );
}
